export const emojiImage = {
  0: require('../assets/sagiriEmoji/1.gif'),
  1: require('../assets/sagiriEmoji/2.gif'),
  2: require('../assets/sagiriEmoji/3.gif'),
  3: require('../assets/sagiriEmoji/4.gif'),
  4: require('../assets/sagiriEmoji/5.gif'),
  5: require('../assets/sagiriEmoji/6.gif'),
  6: require('../assets/sagiriEmoji/7.gif'),
  7: require('../assets/sagiriEmoji/8.gif'),
  8: require('../assets/sagiriEmoji/9.gif'),
  9: require('../assets/sagiriEmoji/10.gif'),
  10: require('../assets/sagiriEmoji/11.gif'),
  11: require('../assets/sagiriEmoji/12.gif'),
  12: require('../assets/sagiriEmoji/13.gif'),
  13: require('../assets/sagiriEmoji/14.gif'),
  14: require('../assets/sagiriEmoji/15.gif'),
  15: require('../assets/sagiriEmoji/16.gif'),
  16: require('../assets/sagiriEmoji/17.gif'),
  17: require('../assets/sagiriEmoji/18.gif'),
  18: require('../assets/sagiriEmoji/19.gif'),
  19: require('../assets/sagiriEmoji/20.gif'),
  20: require('../assets/sagiriEmoji/21.gif'),
  21: require('../assets/sagiriEmoji/22.gif'),
  22: require('../assets/sagiriEmoji/23.gif'),
  23: require('../assets/sagiriEmoji/24.gif'),
  24: require('../assets/sagiriEmoji/25.gif'),
  25: require('../assets/sagiriEmoji/26.gif'),
  26: require('../assets/sagiriEmoji/27.gif'),
  27: require('../assets/sagiriEmoji/28.gif'),
  28: require('../assets/sagiriEmoji/29.gif'),
  29: require('../assets/sagiriEmoji/30.gif'),
};
// for i in ./src/assets/sagiriEmoji/*.gif ; do mv "$i" "${i/-[0-9.]*.gif/.gif}" ; done
